### ISSUE TITLE
Nebula/ECS Infrastructure

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/planetoid-shooter#2]
# Nebula-Flixel
- [x] Try `Ash-Haxe`
- [x] Create ECS; document usage
- [x] See if you can remove `container` from constructors (`entity`? `system`?)
- [x] Fix the builds. The tests don't pass unless you have a dev version of `noor`.
- [x] Write unit tests for `nebula` code
- [x] `Entity.removeComponent` should take a class. Refactor tests (eg. camera system tests)
- [x] Reading params from the URL (Flash: `flash.Lib.current.loaderInfo.parameters` and JS (`haxe.web.Request.getParams()`). And a way to disable it in production.
- [x] Make a fluent interface for `Entity`, possibly with common methods (eg. `size`, `color`, `sprite`, etc.) to get as close to our prototyping helpers for CraftyJS as possible
- [x] Port over more systems/functionality
  - [x] Repeating backgrounds for images
- [x] Nebula code for reading from `config.json` or URL parameters
- [x] Camera system works with `colour` component

**Comment by alihassan0** [comment]
@ashes999 I think assigning tasks here would be easier

**Comment by ashes999** [comment]
Okay @alihassan0 , I've assigned you two tasks:

1) Make the background repeat. (You can use the background from the original prototype, plus the new functionality you just added.)
2) Map is bigger than the view, and the map scrolls to follow the player. This is a larger change that likely requires a new system (camera system?) and maybe some new components.

I have to figure out how to test the actual game code itself. Any suggestions?

**Comment by alihassan0** [comment]
I am not sure what you mean by the actual game code Actually. 

Also here is what I think about the `Camera`. 

making the camera follow player is actually pretty straightforward as far as I know. 
it's just `FlxG.camera.Follow(sprite)`

but I don't think that this is viable in this architecture. so here is what I am proposing. 

we make a new system called `CameraSystem` and a new Component called `CameraControlComponent`

`CameraControlComponent`  which takes 2 arguments in the constructor
`useDefault` which controls whether to use the default FlxG.camera 
`target` which controls whether the camera should follow such a player.

this way we can make a camera that follows the player if params are `(true, this)`
or we can create a generic camera if params are `(false,null)`

**Comment by ashes999** [comment]
Yes, this is more or less what my vision was for this feature. Let's move this discussion into a new issue (#4).

**Comment by ashes999** [comment]
@alihassan0 don't forget to do the game/prototype part of the repeated background (use the repeated background from the prototype in game)
