### ISSUE TITLE
Camera System and Component

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/planetoid-shooter#4]
For Planetoid, we need to create functionality that allows the caller to specify which entity the camera should follow. For now, we only need to support sprites.

Since we're working together for the first time, it's safer to over-describe the requirements in details.
- `CameraComponent` class. Doesn't have any fields
- `FollowCameraSystem`.
  - Constructor should specify that it requires entities with a `CameraComponent` and a `SpriteComponent`
  - `Update` should throw an exception if there are more than one entities with the camera component
  - `Update` should call `FlxG.camera.Follow(sprite)` to follow the one entity with the component
  - We shouldn't call `FlxG.camera.Follow(sprite)` every update (we need to internally track which entity we're updating). If the entity changes (not the sprite, but the entity), we need to track that new entity.
  - If we were following an entity, and now there are no entities to follow, stop following the current entity.
- Tests for all of this functionality

Is that clear enough?

I also favour (extreme) simplicity for APIs. We don't need to support `useDefault` and `target`, or assume that more than one camera exists. We can tackle those changes later.

**Comment by ashes999** [comment]
What do you think of this @alihassan0 ?

**Comment by alihassan0** [comment]
sounds good .. i will get to it tomorrow in shaa' Allah

**Comment by ashes999** [comment]
InshaAllah. I added a note that we should stop following the entity if there are no entities left to follow. I'm trying to simplify the use case for when someone wants to change which entity to track; they juts need to:
- Remove the component from the current entity
- Add it to the new entity

I hope that works. Let me know if you need help testing it ...

**Comment by alihassan0** [comment]
I was thinking instead of throwing errors if more than one instance of `CameraComponent` exists . we can instead just use the latest one. 

which maybe useful in some cases where you would like to change the camera focus temporarily.

**Comment by ashes999** [comment]
I would rather throw an error. 

Having two instances doesn't make sense. We're effectively ignoring all but the most recent one. I would classify this as a developer error/mistake.

"Fail fast" is a good practice to detect errors early. It's also fairly easy for us to detect this and throw an error.

The workflow to change camera focus temporarily is also fairly easy: just remove and re-add the component wherever you want to focus.
